"""Shared public service URL defaults for daily artifact links."""

DEFAULT_BACKUP_HOST = "dg2fizz.ikor.intel.com"
DAILY_FILE_BROWSER_PORT = 8081
DEFAULT_DAILY_FILE_BROWSER_ORIGIN = f"http://{DEFAULT_BACKUP_HOST}:{DAILY_FILE_BROWSER_PORT}"
DEFAULT_DAILY_REPORT_BASE_URL = f"{DEFAULT_DAILY_FILE_BROWSER_ORIGIN}/daily2"
