site_name: run_daily Wiki
site_description: Internal documentation for run_daily
site_url: http://127.0.0.1:8080

nav:
  - Home: index.md
  - Web Services:
      - Jenkins: web_services/jenkins.md
  - Operations:
      - Caddy: operations/caddy.md

theme:
  name: material
  language: en
  features:
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share

plugins:
  - search
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.superfences

strict: true
